/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        volt: {
          bg:       '#050816',
          card:     '#0f172a',
          border:   '#1e293b',
          cyan:     '#22d3ee',
          pink:     '#ec4899',
          green:    '#10b981',
          amber:    '#f59e0b',
          red:      '#ef4444',
          purple:   '#8b5cf6',
          textPri:  '#f1f5f9',
          textSec:  '#94a3b8',
          textMute: '#475569',
        },
        // MD3 style premium theme colors from mockup
        "tertiary-container": "#23ebb8",
        "surface-bright": "#353a3f",
        "secondary-fixed-dim": "#cdbdff",
        "tertiary-fixed": "#45fec9",
        "surface": "#0f1419",
        "surface-container-high": "#252a30",
        "on-tertiary": "#003829",
        "on-surface": "#dee3ea",
        "outline-variant": "#3b494c",
        "surface-container-lowest": "#0a0f13",
        "on-background": "#dee3ea",
        "primary-fixed": "#9cf0ff",
        "on-surface-variant": "#bac9cc",
        "on-primary-fixed": "#001f24",
        "on-primary-fixed-variant": "#004f58",
        "primary": "#c3f5ff",
        "inverse-primary": "#006875",
        "primary-fixed-dim": "#00daf3",
        "on-error": "#690005",
        "surface-container-low": "#171c21",
        "on-tertiary-fixed-variant": "#00513d",
        "inverse-surface": "#dee3ea",
        "tertiary": "#a1ffdc",
        "on-secondary-container": "#c0acff",
        "surface-container-highest": "#30353b",
        "secondary-fixed": "#e8deff",
        "on-secondary": "#370096",
        "on-tertiary-fixed": "#002117",
        "surface-tint": "#00daf3",
        "tertiary-fixed-dim": "#00e1ae",
        "primary-container": "#00e5ff",
        "outline": "#849396",
        "on-secondary-fixed-variant": "#4f00d0",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#2c3136",
        "secondary-container": "#5203d5",
        "error-container": "#93000a",
        "surface-dim": "#0f1419",
        "on-primary-container": "#00626e",
        "on-tertiary-container": "#00654d",
        "on-secondary-fixed": "#20005f",
        "surface-variant": "#30353b",
        "secondary": "#cdbdff",
        "on-primary": "#00363d",
        "surface-container": "#1b2025",
        "error": "#ffb4ab",
        "background": "#0f1419"
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        body:    ['"Inter"', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'monospace'],
        headline: ['"Inter"', 'sans-serif'],
      },
      boxShadow: {
        cyan:   '0 4px 20px rgba(34,211,238,0.04)',
        pink:   '0 4px 20px rgba(236,72,153,0.04)',
        green:  '0 4px 20px rgba(16,185,129,0.04)',
        card:   '0 10px 30px rgba(0, 0, 0, 0.2)',
      },
      backdropBlur: {
        xs: '2px',
      },
      animation: {
        'pulse-cyan':  'pulse-cyan 2s cubic-bezier(0.4,0,0.6,1) infinite',
        'pulse-glow': 'pulse-glow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float':       'float 3s ease-in-out infinite',
        'float-slow':  'float 8s ease-in-out infinite',
        'slide-up':    'slide-up 0.3s ease-out',
        'coin-burst':  'coin-burst 0.6s ease-out forwards',
      },
      keyframes: {
        'pulse-cyan': {
          '0%,100%': { opacity: 0.8 },
          '50%':     { opacity: 1 },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: 1, transform: 'scale(1)' },
          '50%': { opacity: .92, transform: 'scale(1.005)' },
        },
        'float': {
          '0%,100%': { transform: 'translateY(0px)' },
          '50%':     { transform: 'translateY(-8px)' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        'coin-burst': {
          '0%':   { transform: 'scale(0) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'scale(1.5) rotate(360deg)', opacity: '0' },
        },
      },
    },
  },
  plugins: [],
}
